apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rocky
  name: rocky
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rocky
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rocky
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
